package com.ecommerce.bicicle.constants;

public class TransactionStatus {

    public TransactionStatus() { }
    /**
     *
     */
    public static final String TRANSACT_STATUS_BEFORE_TRANSACTION = "BEFORE_TRANSACTION";
    public static final String TRANSACT_STATUS_CANCEL_TRANSACTION = "CANCEL_TRANSACTION";
    public static final String TRANSACT_STATUS_CLIENT_AUTHORIZATION = "CLIENT_AUTHORIZATION";
    public static final String TRANSACT_STATUS_AFTER_TRANSACTION_APPROVED = "APPROVED_NOT_AUTHORIZE_YET";
    public static final String TRANSACT_STATUS_AFTER_TRANSACTION_APPROVED_AND_AUTHORIZED = "APPROVED_AND_AUTHORIZED";
    public static final String TRANSACT_STATUS_AFTER_TRANSACTION_FAILED = "AFTER_TRANSACTION_FAILED";
    public static final String TRANSACT_STATUS_USER_VENDOR_NOTIFIED = "USER_VENDOR_NOTIFIED";
    public static final String TRANSACT_STATUS_USER_SALER_NOTIFIED = "USER_SALER_NOTIFIED";
    public static final String TRANSACT_STATUS_USER_ADMINISTRATORS_NOTIFIED = "USER_ADMINISTRATORS_NOTIFIED";
    public static final String TRANSACT_STATUS_USER_VENDOR_INCLUSE_TRACK_ID = "USER_VENDOR_INCLUSE_TRACK_ID";
}
